### PR TITLE
Update raysession_fr_FR.ts

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
@Houston4444 : ping

**Comment by Houston4444** [comment]
Siret, i am in trip. I'll look this monday au plus tard.


Le 22 févr. 2018 00:11, "Olivier Humbert" <notifications@github.com> a
écrit :

**Comment by trebmuh** [comment]
OK

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
